---
email: swysocki@gmail.com
git_name: "Scott Wysocki"
default_shell: "zsh"
repos_path: "devel/repos"
python_version: "3.8"
neovim_version: "0.9.1"
neovim_hash: "262892176e21da0902c4f0b1e027d54d21b4bcae6b0397afccd8a81b476c3055"
vim_version: "v9.0.1603"
