---
- name: make config directories
  ansible.builtin.file:
    path: "{{ home_path }}/{{ item }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ group_name }}"
  with_items:
    - '.config/nvim/'
    - '.config/yamllint'
    - '.config/wezterm'

- name: clone dotfiles
  ansible.builtin.git:
    repo: https://github.com/swysocki/dotfiles
    dest: "{{ home_path }}/{{ repos_path }}/dotfiles"
    depth: 1

- name: link configs
  ansible.builtin.file:
    src: "{{ home_path }}/{{ repos_path }}/dotfiles/{{ item.source }}"
    dest: "{{ home_path }}/{{ item.destination }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ group_name }}"
    force: yes
    state: link
  with_items:
    - {source: 'vimrc', destination: '.vimrc'}
    - {source: 'config/nvim', destination: '.config/nvim'}
    - {source: 'config/tmux.conf', destination: '.tmux.conf'}
    - {source: 'config/zshrc', destination: '.zshrc'}
    - {source: 'config/yamllint.yml', destination: '.config/yamllint/config'}
    - {source: 'config/alias.zsh', destination: '.oh-my-zsh/custom/alias.zsh'}
    - {source: 'config/wezterm.lua', destination: '.config/wezterm/wezterm.lua'}
