---
- name: install common tools
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - acl
    - fd-find
    - fzf
    - git
    - htop
    - jsonnet
    - libfuse2
    - pipx
    - python3-pip
    - python3-venv
    - ripgrep
    - shellcheck
    - tmux
    - virtualenv
    - zsh
  become: true
  when: install_ubuntu
