---
- name: install common tools
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - acl
    - fd-find
    - fzf
    - git
    - htop
    - jsonnet
    - libfuse2
    - pipx
    - python3-pip
    - python3-venv
    - ripgrep
    - shellcheck
    - tmux
    - virtualenv
    - zsh
  become: true
  when: install_ubuntu

- name: install Brew packages
  community.general.homebrew:
    name: "{{ item }}"
  loop:
    - bash
    - fzf
    - git
    - hadolint
    - jq
    - jsonnet
    - pipx
    - pyright
    - python@{{ python_version }}
    - ripgrep
    - shellcheck
    - shfmt
    - virtualenv
    - wget
    - yamllint
    - zsh
